## DATA CLEANING & EDA

In [432]:
import pandas as pd
import matplotlib as plt

In [433]:
df = pd.read_csv('uneguicar1.csv')

In [434]:
df

prices manufacturers  manufactured_years  entry_years engine_sizes  \
0       29.2  Prius 40, 41                2012         2024        1.8 л   
1      120.0        Patrol                2016         2016        5.2 л   
2       79.0         Camry                2022         2024        1.5 л   
3      560.0            LX                2023         2023        3.5 л   
4       14.6         NV200                2012         2024        1.6 л   
...      ...           ...                 ...          ...          ...   
2995     6.5        Spacio                2002         2010        1.5 л   
2996    35.0         Бусад                2001         2012        4.6 л   
2997     7.8       Insight                2009         2019        1.3 л   
2998    57.0            GS                2016         2024        3.0 л   
2999    40.0      Vellfire                2009         2024        2.4 л   

     transmissions fuel_types    mileages  
0          Автомат    Хайбрид  179000 км.  
1          Автомат     Бензин  100000 км.  
2          Автомат    Хайбрид   13000 км.  
3          Автомат     Бензин    3400 км.  
4          Автомат     Бензин  189000 км.  
...            ...        ...         ...  
2995       Автомат     Бензин       1 км.  
2996       Автомат     Бензин     200 км.  
2997       Автомат    Хайбрид     200 км.  
2998       Автомат    Хайбрид  150000 км.  
2999       Автомат     Бензин  188000 км.  

[3000 rows x 8 columns]

In [435]:
df['prices'] = df['prices'] * 1000000

In [436]:
df['prices']

0        29200000.0
1       120000000.0
2        79000000.0
3       560000000.0
4        14600000.0
           ...     
2995      6500000.0
2996     35000000.0
2997      7800000.0
2998     57000000.0
2999     40000000.0
Name: prices, Length: 3000, dtype: float64

In [437]:
df['prices'] = df['prices'].astype(int)

In [438]:
df['prices']

0        29200000
1       120000000
2        79000000
3       560000000
4        14600000
          ...    
2995      6500000
2996     35000000
2997      7800000
2998     57000000
2999     40000000
Name: prices, Length: 3000, dtype: int32

In [439]:
df

prices manufacturers  manufactured_years  entry_years engine_sizes  \
0      29200000  Prius 40, 41                2012         2024        1.8 л   
1     120000000        Patrol                2016         2016        5.2 л   
2      79000000         Camry                2022         2024        1.5 л   
3     560000000            LX                2023         2023        3.5 л   
4      14600000         NV200                2012         2024        1.6 л   
...         ...           ...                 ...          ...          ...   
2995    6500000        Spacio                2002         2010        1.5 л   
2996   35000000         Бусад                2001         2012        4.6 л   
2997    7800000       Insight                2009         2019        1.3 л   
2998   57000000            GS                2016         2024        3.0 л   
2999   40000000      Vellfire                2009         2024        2.4 л   

     transmissions fuel_types    mileages  
0          Автомат    Хайбрид  179000 км.  
1          Автомат     Бензин  100000 км.  
2          Автомат    Хайбрид   13000 км.  
3          Автомат     Бензин    3400 км.  
4          Автомат     Бензин  189000 км.  
...            ...        ...         ...  
2995       Автомат     Бензин       1 км.  
2996       Автомат     Бензин     200 км.  
2997       Автомат    Хайбрид     200 км.  
2998       Автомат    Хайбрид  150000 км.  
2999       Автомат     Бензин  188000 км.  

[3000 rows x 8 columns]

In [440]:
df['transmissions'] = df['transmissions'].replace('Автомат', 'Automat')

In [441]:
df['transmissions']

0       Automat
1       Automat
2       Automat
3       Automat
4       Automat
         ...   
2995    Automat
2996    Automat
2997    Automat
2998    Automat
2999    Automat
Name: transmissions, Length: 3000, dtype: object

In [442]:
df['fuel_types'] = df['fuel_types'].replace('Хайбрид', 'Hybrid')

In [443]:
df['fuel_types'] = df['fuel_types'].replace('Бензин', 'Petrol')

In [444]:
df['fuel_types'] = df['fuel_types'].replace('Газ', 'Gas')

In [445]:
df['fuel_types'] = df['fuel_types'].replace('Дизель', 'Diesel')

In [446]:
df['fuel_types']

0       Hybrid
1       Petrol
2       Hybrid
3       Petrol
4       Petrol
         ...  
2995    Petrol
2996    Petrol
2997    Hybrid
2998    Hybrid
2999    Petrol
Name: fuel_types, Length: 3000, dtype: object

In [447]:
df['fuel_types'].value_counts()

Petrol    1650
Hybrid    1250
Gas         50
Diesel      50
Name: fuel_types, dtype: int64

In [448]:
df['engine_sizes'] = df['engine_sizes'].replace('Цахилгаан', 'Electric')

In [449]:
df['engine_sizes'] = df['engine_sizes'].str.replace(' л', '')

In [450]:
df['engine_sizes']

0       1.8
1       5.2
2       1.5
3       3.5
4       1.6
       ... 
2995    1.5
2996    4.6
2997    1.3
2998    3.0
2999    2.4
Name: engine_sizes, Length: 3000, dtype: object

In [451]:
df['mileages'] = df['mileages'].str.replace(' км.', '')

C:\Users\mnkhz\AppData\Local\Temp\ipykernel_18792\2901983577.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['mileages'] = df['mileages'].str.replace(' км.', '')


In [452]:
df['mileages']

0       179000
1       100000
2        13000
3         3400
4       189000
         ...  
2995         1
2996       200
2997       200
2998    150000
2999    188000
Name: mileages, Length: 3000, dtype: object

In [453]:
df['manufacturers'] = df['manufacturers'].replace('Бусад', 'Other')

In [454]:
df

prices manufacturers  manufactured_years  entry_years engine_sizes  \
0      29200000  Prius 40, 41                2012         2024          1.8   
1     120000000        Patrol                2016         2016          5.2   
2      79000000         Camry                2022         2024          1.5   
3     560000000            LX                2023         2023          3.5   
4      14600000         NV200                2012         2024          1.6   
...         ...           ...                 ...          ...          ...   
2995    6500000        Spacio                2002         2010          1.5   
2996   35000000         Other                2001         2012          4.6   
2997    7800000       Insight                2009         2019          1.3   
2998   57000000            GS                2016         2024          3.0   
2999   40000000      Vellfire                2009         2024          2.4   

     transmissions fuel_types mileages  
0          Automat     Hybrid   179000  
1          Automat     Petrol   100000  
2          Automat     Hybrid    13000  
3          Automat     Petrol     3400  
4          Automat     Petrol   189000  
...            ...        ...      ...  
2995       Automat     Petrol        1  
2996       Automat     Petrol      200  
2997       Automat     Hybrid      200  
2998       Automat     Hybrid   150000  
2999       Automat     Petrol   188000  

[3000 rows x 8 columns]

In [455]:
print(df['transmissions'].unique())
print(df['fuel_types'].unique())

['Automat']
['Hybrid' 'Petrol' 'Gas' 'Diesel']


In [456]:
df.replace({'transmissions':{'Automat':0}}, inplace=True)

In [457]:
df.replace({'fuel_types':{'Hybrid':0, 'Petrol':1, 'Gas':2, 'Diesel':3}}, inplace=True)

In [458]:
df.replace({'engine_sizes':{'Electric':1}}, inplace=True)

In [459]:
df.rename(columns={'manufacturers': 'model'}, inplace=True)
df.rename(columns={'prices': 'price'}, inplace=True)
df.rename(columns={'manufactured_years': 'manufactured_year'}, inplace=True)
df.rename(columns={'entry_years': 'entry_year'}, inplace=True)
df.rename(columns={'engine_sizes': 'engine_size'}, inplace=True)
df.rename(columns={'transmissions': 'transmission'}, inplace=True)
df.rename(columns={'mileages': 'mileage'}, inplace=True)

In [460]:
df

price         model  manufactured_year  entry_year engine_size  \
0      29200000  Prius 40, 41               2012        2024         1.8   
1     120000000        Patrol               2016        2016         5.2   
2      79000000         Camry               2022        2024         1.5   
3     560000000            LX               2023        2023         3.5   
4      14600000         NV200               2012        2024         1.6   
...         ...           ...                ...         ...         ...   
2995    6500000        Spacio               2002        2010         1.5   
2996   35000000         Other               2001        2012         4.6   
2997    7800000       Insight               2009        2019         1.3   
2998   57000000            GS               2016        2024         3.0   
2999   40000000      Vellfire               2009        2024         2.4   

      transmission  fuel_types mileage  
0                0           0  179000  
1                0           1  100000  
2                0           0   13000  
3                0           1    3400  
4                0           1  189000  
...            ...         ...     ...  
2995             0           1       1  
2996             0           1     200  
2997             0           0     200  
2998             0           0  150000  
2999             0           1  188000  

[3000 rows x 8 columns]

In [461]:
df['model'].value_counts()

Prius 40, 41        350
LX                  200
Crown               150
Prius 30            150
Land Cruiser 200    100
Harrier             100
Patrol              100
Axio                100
Vellfire            100
GS                  100
Noah                 50
Forester             50
C-HR                 50
Q5                   50
Corolla              50
Delica               50
Santa-Fe             50
Note                 50
Serena               50
GX                   50
Spacio               50
Other                50
Prius 20             50
C-Class              50
Prius 10, 11         50
E-Class              50
Camry                50
NV200                50
Swift                50
Optima/K5            50
S-Class              50
Outlander            50
ES                   50
Cayenne              50
Mazda3 Axela         50
Escape               50
Vanette              50
Townace              50
RX                   50
Hilux                50
Insight              50
Name: model, dty

In [462]:
df.replace({'model':{'Prius 40, 41':4, 'Prius 30':3, 'Prius 20':2, 'Prius 10, 11':1, 'LX':0, 
                    'Crown':0, 'Land Cruiser 200':0, 'Harrier':0, 'Patrol':0, 'Axio':0, 'Vellfire':0,
                    'GS':0, 'Noah':0, 'Forester':0, 'C-HR':0, 'Q5':0, 'Corolla':0,
                    'Delica':0, 'Santa-Fe':0, 'Note':0, 'Serena':0, 'GX':0, 'Spacio':0,
                    'Other':0, 'C-Class':0, 'E-Class':0, 'Camry':0, 'NV200':0, 'Swift':0,
                    'Optima/K5':0, 'S-Class':0, 'Outlander':0, 'ES':0, 'Cayenne':0, 'Mazda3 Axela':0,
                    'Escape':0, 'Vanette':0, 'Townace':0, 'RX':0, 'Hilux':0, 'Insight':0,
                    }}, inplace=True)

In [463]:
df

price  model  manufactured_year  entry_year engine_size  \
0      29200000      4               2012        2024         1.8   
1     120000000      0               2016        2016         5.2   
2      79000000      0               2022        2024         1.5   
3     560000000      0               2023        2023         3.5   
4      14600000      0               2012        2024         1.6   
...         ...    ...                ...         ...         ...   
2995    6500000      0               2002        2010         1.5   
2996   35000000      0               2001        2012         4.6   
2997    7800000      0               2009        2019         1.3   
2998   57000000      0               2016        2024         3.0   
2999   40000000      0               2009        2024         2.4   

      transmission  fuel_types mileage  
0                0           0  179000  
1                0           1  100000  
2                0           0   13000  
3                0           1    3400  
4                0           1  189000  
...            ...         ...     ...  
2995             0           1       1  
2996             0           1     200  
2997             0           0     200  
2998             0           0  150000  
2999             0           1  188000  

[3000 rows x 8 columns]

In [464]:
df['model'].value_counts()

0    2400
4     350
3     150
1      50
2      50
Name: model, dtype: int64

## Splitting Data into Features and Labels

In [465]:
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import mean_absolute_error 
from xgboost import XGBRegressor 
from sklearn.preprocessing import StandardScaler

In [466]:
x = df.drop(['price'], axis=1).values
y = df['price']
x

array([[4, 2012, 2024, ..., 0, 0, '179000'],
       [0, 2016, 2016, ..., 0, 1, '100000'],
       [0, 2022, 2024, ..., 0, 0, '13000'],
       ...,
       [0, 2009, 2019, ..., 0, 0, '200'],
       [0, 2016, 2024, ..., 0, 0, '150000'],
       [0, 2009, 2024, ..., 0, 1, '188000']], dtype=object)

In [467]:
x

array([[4, 2012, 2024, ..., 0, 0, '179000'],
       [0, 2016, 2016, ..., 0, 1, '100000'],
       [0, 2022, 2024, ..., 0, 0, '13000'],
       ...,
       [0, 2009, 2019, ..., 0, 0, '200'],
       [0, 2016, 2024, ..., 0, 0, '150000'],
       [0, 2009, 2024, ..., 0, 1, '188000']], dtype=object)

## Standardizing Data

In [468]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [469]:
standardized_x = scaler.transform(x)
standardized_x

array([[ 2.38365647, -0.2422859 ,  0.76885766, ...,  0.        ,
        -1.04750391, -0.12778574],
       [-0.47673129,  0.54350621, -1.21529113, ...,  0.        ,
         0.60644963, -0.13121639],
       [-0.47673129,  1.72219437,  0.76885766, ...,  0.        ,
        -1.04750391, -0.13499444],
       ...,
       [-0.47673129, -0.83162998, -0.47123534, ...,  0.        ,
        -1.04750391, -0.1355503 ],
       [-0.47673129,  0.54350621,  0.76885766, ...,  0.        ,
        -1.04750391, -0.12904509],
       [-0.47673129, -0.83162998,  0.76885766, ...,  0.        ,
         0.60644963, -0.12739491]])

In [470]:
x = standardized_x
y = df['price']

In [471]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=.1, random_state=42)
print(x.shape, x_train.shape, x_test.shape)
print(y.shape, y_train.shape, y_test.shape)

(3000, 7) (2700, 7) (300, 7)
(3000,) (2700,) (300,)


## XGB Regressor

In [472]:
xgb_model = XGBRegressor()

In [473]:
xgb_model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [474]:
x_train

array([[-0.47673129,  0.34705818,  0.76885766, ...,  0.        ,
        -1.04750391, -0.12717778],
       [ 1.66855953, -0.63518195,  0.76885766, ...,  0.        ,
        -1.04750391, -0.13074305],
       [-0.47673129,  0.34705818,  0.76885766, ...,  0.        ,
        -1.04750391, -0.12717778],
       ...,
       [ 1.66855953, -0.2422859 ,  0.76885766, ...,  0.        ,
        -1.04750391, -0.13047815],
       [-0.47673129,  1.13285029,  0.76885766, ...,  0.        ,
        -1.04750391, -0.13247574],
       [-0.47673129, -0.2422859 ,  0.02480186, ...,  0.        ,
         0.60644963, -0.12774232]])

## Model Evaluation

In [475]:
training_data_pred = xgb_model.predict(x_train)
score_1 = metrics.r2_score(y_train, training_data_pred)

mae = metrics.mean_absolute_error(y_train, training_data_pred)

print('R2 score on training data :', score_1)
print('Mean absolute error on training data: ', mae)

R2 score on training data : 0.9999908892039365
Mean absolute error on training data:  49294.72814814815


In [476]:
test_data_pred = xgb_model.predict(x_test)
score_1 = metrics.r2_score(y_test, test_data_pred)

mae = metrics.mean_absolute_error(y_test, test_data_pred)

print('R2 score on training data :', score_1)
print('Mean absolute error on training data: ', mae)

R2 score on training data : 0.9999903258908323
Mean absolute error on training data:  56411.113333333335


## Making Predictions

In [477]:
input_data = (4,2012,2024,1.8,0,0,179000)

input_changed= np.array(input_data).reshape(1,-1)

std_input = scaler.transform(input_changed)

prediction = xgb_model.predict(std_input)
print(prediction)

print('This car price prediction is :' , prediction)

[29199994.]
This car price prediction is : [29199994.]


## Saving Model and Scaler

In [428]:
import joblib

joblib.dump(xgb_model, 'xgb_model.pkl')

joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']